MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrain_models/model.pt"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
    FREEZE_CONV_BODY_AT: -1
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("humancrowd_coco_train", )
  TEST: ("humancrowd_coco_val", )
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 3000000
  IMS_PER_BATCH: 1
  WARMUP_METHOD: "constant"
