MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrain_models/R-50.pkl"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("head_offset_coco_train", )
  TEST: ("head_offset_coco_val", )
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.0001
  EPOCHES: 30
  IMS_PER_BATCH: 2
  WARMUP_METHOD: "constant"
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 100
  #STEPS: (210000, 250000)
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "res/head_off3" # Adam:: test1:0.0001, test2:0.00001   SGD:: test3:0.001, test4:0.01
